# Generated by Django 4.0.8 on 2022-12-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000, unique=True)),
                ('language', models.CharField(choices=[('en', 'english'), ('ar', 'arabic'), ('fr', 'french')], max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
